apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/instance: myntra-clone-app-02
  name: myntra-clone-app-deployment-resource-02
  #namespace: apps101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        #image: sevenajay/myntra:latest
        image: rover102/myntra-clone-app-01:32
        ports:
        - containerPort: 3000   # Use port 3000
