apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/instance: myntra-clone-app-02
  name: myntra-clone-app-service-resource-02
  #namespace: apps101
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
